import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import ConditionalLayout from './components/ConditionalLayout';
import { AuthProvider } from './providers/AuthProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'DigiKara',
  description: 'Generated by create next app',
  icons: {
    icon: '/Logo.svg',
    shortcut: '/Logo.svg',
    apple: '/Logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen `}>
        <AuthProvider>
          <ConditionalLayout />
          <main>{children}</main>
        </AuthProvider>
        <Toaster 
          position="top-center" 
          richColors 
          closeButton 
          duration={2000}
          toastOptions={{
            style: {
              borderRadius: '16px',
              direction: 'rtl',
              textAlign: 'right',
            },
          }}
        />
      </body>
    </html>
  );
}
